import Credit from "./ourstorycredits"
import { Link } from "react-router-dom"
function OurStory()
{
return(
    <div className="storyContainer">
        <div className="navbar">
            <div className="temp">
                <h3>CAREER CONNECT</h3>
                <div className="navMenu">
                    <Link to="/career_connect/">HOME</Link>
                    <Link to="/career_connect/OurStory">OUR STORY</Link>
                    <Link to="/career_connect/contactUs">CONTACT US</Link>
                </div>
            </div>
        </div>
        <div className="ourStoryImg">
            <h1>Our Story</h1>
        </div>
        <div className="storyFlex">
            <div>
                <h1>Lorem ipsum dolor sit amet.</h1>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Labore obcaecati quae nemo a voluptatem cumque illo odit, veritatis pariatur sunt at ducimus, ea reiciendis soluta beatae fugit aliquam nesciunt consequatur. Aperiam est enim labore dolorem, explicabo consequatur blanditiis nam ex laboriosam voluptate eos quaerat reprehenderit itaque? Quod, maiores! Possimus ducimus repellat minima et, laborum quo, asperiores natus molestias consequatur quibusdam facere corrupti voluptatum nesciunt expedita maiores, rem maxime facilis fuga aperiam perferendis fugiat. Minima consectetur veniam quidem voluptatum error nostrum quod maiores adipisci itaque dolorum sed similique earum quia ratione, dolore voluptatibus eaque corporis est iste ipsam. Sequi quis dolor numquam maiores asperiores aut saepe? Dolore vel blanditiis placeat atque tempora rerum quidem optio illo corporis repellendus hic temporibus nulla fuga molestias earum error ex nostrum, maiores reiciendis animi repudiandae assumenda ea. Aperiam nam officia labore nisi sed tenetur necessitatibus ab ducimus exercitationem quam iusto numquam recusandae cumque repudiandae fugiat reiciendis accusamus, dolorem minima quibusdam iste nesciunt? Ea enim dolores harum. Aut, tenetur praesentium itaque dolorum aliquam saepe, odio mollitia aperiam omnis cum enim a? Vero molestiae quae fuga consectetur ut fugiat, soluta perferendis deserunt ad eos necessitatibus ratione quibusdam autem iusto excepturi ipsa minus quas odit architecto? Dignissimos, veniam?</p>
                <h1>consectetur adipisicing elit aliquid</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque, culpa temporibus tenetur saepe sunt eum dolor fugit obcaecati ratione labore, sed blanditiis. Error ipsam ratione alias magni temporibus, hic aperiam consequatur ipsum dicta odio atque ea debitis ducimus quibusdam qui et mollitia numquam quaerat cupiditate similique, itaque distinctio unde? Eaque dolores ut esse quae quos accusantium assumenda cum velit, veritatis temporibus quis ex! Voluptate eaque dolor, repellendus nostrum praesentium soluta aspernatur nobis excepturi itaque eligendi blanditiis eveniet doloribus aliquam voluptatum libero quasi et eius consectetur in ab maxime non doloremque iure assumenda! Magnam laudantium exercitationem, commodi maxime impedit accusantium qui?</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sit, deserunt praesentium incidunt tempora nulla vero quisquam doloremque eligendi tempore, voluptates consequatur iste dignissimos exercitationem, omnis placeat aspernatur eius molestias laudantium dolorem consectetur vitae! Necessitatibus rem officiis fuga rerum impedit distinctio facilis quidem quae porro fugit eius inventore reprehenderit corporis numquam, mollitia eos molestiae ex aperiam, reiciendis vitae ratione. Deserunt nulla sequi tenetur voluptas sed, error odit corporis dolorem? Maxime, perspiciatis, eveniet accusamus architecto consectetur, provident incidunt mollitia labore placeat beatae neque alias sunt molestiae amet porro corporis? Vel quo, maiores excepturi nam nobis consequatur unde eligendi, distinctio enim obcaecati similique?</p>
                <h1>Lorem ipsum dolor sit amet consectetur adipisicing.</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti temporibus perspiciatis rem numquam fugit, dolor facere veniam minima ab ratione autem accusamus. Officia placeat aut corrupti recusandae, iure repellat porro vel cupiditate animi, maiores provident possimus modi quasi eveniet temporibus veritatis obcaecati accusantium ipsam dicta ullam adipisci numquam, tenetur sit. Vel natus suscipit unde ad ab optio, repellendus excepturi iste vero modi quam eligendi possimus iure numquam tempora a fugiat sapiente, obcaecati consequatur? Fugiat id nulla ducimus molestias harum dolorum maxime assumenda voluptatem quia quasi aliquam commodi ab deserunt fuga aperiam, perspiciatis tempora quibusdam et officia? Amet similique dignissimos minima!</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel possimus praesentium in sit nemo error quam officia, voluptas odio dolorem deleniti quae iusto quisquam eius cupiditate eaque quaerat esse minus asperiores at temporibus nulla quas nobis? Corrupti error voluptatum numquam veritatis doloremque, aspernatur quae saepe blanditiis animi nam maiores provident.</p>
            </div>
            <div>
                <h1>Lorem ipsum dolor sit amet consectetur.</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio porro consequatur, ipsam earum ratione facere. Dolores ipsam recusandae suscipit a ab voluptate consequatur nam explicabo labore, optio impedit, in magni quis facere accusantium, natus sequi quidem reiciendis voluptas error iste ipsum amet. Id corrupti velit qui consectetur! Quasi, tempora nulla magni voluptates ipsum magnam! Illo mollitia earum dignissimos quia vitae quam illum beatae non excepturi nulla. Sint natus quae ea fugit ut aperiam alias omnis soluta architecto deleniti labore neque quis, nesciunt corporis! Perspiciatis accusantium cumque aperiam quo, libero possimus, quibusdam tempore, distinctio est corrupti cum in obcaecati quas? Ex officia expedita voluptatum culpa necessitatibus et ab quod beatae! Ratione, in odio, tempore quisquam nihil laudantium molestiae, molestias hic sunt commodi ipsum cum. Quam nihil ullam minus labore error quae totam vel sapiente eum a repellat beatae dolore, hic voluptatem, maiores ea? Sunt, saepe, adipisci aut at officia eos molestias cumque deserunt asperiores eveniet mollitia ut commodi autem doloremque ullam voluptas impedit ratione repudiandae ipsum reiciendis ab illo error amet quisquam. Libero fugit, repudiandae dignissimos veniam facilis vel tempora, deserunt numquam, deleniti quia enim accusantium rem. Mollitia aut dolor facere quisquam aspernatur pariatur deleniti maiores nihil cupiditate. Ipsam dicta assumenda, quam quasi maxime excepturi. Iste repellat error maiores corporis totam esse, alias repellendus, tempora laboriosam iusto, numquam dolorum? Doloribus, quod totam cupiditate, sequi, corporis impedit voluptates ducimus consequuntur accusantium dolorem cum officia doloremque quas nesciunt saepe quaerat? Ipsa numquam laudantium aspernatur aperiam quo eveniet iste sequi voluptatibus aliquid, obcaecati nobis, suscipit enim. Perferendis magnam doloribus fuga perspiciatis numquam magni sit dolorem veritatis, excepturi expedita consectetur quam accusantium in omnis tempore alias rem eius? Numquam deserunt facilis repudiandae dolorem expedita perspiciatis mollitia iusto dignissimos ad sint necessitatibus cupiditate quos ut, itaque doloremque vitae consequuntur excepturi totam nobis. Nam totam soluta quia!</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis rem odio aut, officia harum facere neque, enim nesciunt commodi perferendis corporis provident! Cupiditate neque, obcaecati atque distinctio ab exercitationem! Sapiente exercitationem corrupti nisi. Quae modi numquam id quia voluptate vero magnam distinctio maiores quisquam, exercitationem atque voluptatem est illum, delectus, voluptas praesentium. Doloremque minima perferendis eligendi doloribus vel, nisi officia totam adipisci repudiandae ex soluta cupiditate iure consequatur? Earum molestiae dolores mollitia quod, quae consequatur aspernatur minus sunt laudantium rerum quaerat debitis eveniet iusto, reiciendis nihil qui, incidunt repellendus sed labore doloremque? Eum, fuga ducimus. Fugit natus sunt modi minus!</p>
                <h1>Lorem ipsum dolor sit.</h1>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa, fugit! Asperiores cum ipsum vero magnam fugit fuga laboriosam. Corrupti suscipit eum voluptatem repellendus molestiae aperiam quidem dolores fugit aspernatur, facere rem sit obcaecati voluptas consequatur? Sint totam deserunt saepe nisi quisquam qui voluptate natus, quasi, assumenda beatae quidem, obcaecati voluptas architecto deleniti ipsam eveniet officiis. Optio autem unde rem sit! Fuga similique amet facere laboriosam cupiditate obcaecati distinctio iure nobis impedit deleniti, consequuntur, vero rerum vitae voluptatem omnis accusamus officia autem ut voluptates? Dolorum magnam aperiam nesciunt earum deserunt sunt voluptas totam, maxime a deleniti. Eligendi, officiis corporis. Tenetur, quos.</p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. At ab reiciendis, nobis illum aut hic perspiciatis modi pariatur maxime labore consequatur laboriosam omnis deleniti tempora adipisci sunt amet debitis quae harum. Numquam nemo rerum perspiciatis tempora ex non blanditiis voluptatem error, consectetur ipsa? Quasi, dolor. Incidunt omnis laborum, nulla laboriosam ratione eligendi nostrum inventore maxime quis laudantium repudiandae nemo. Molestiae nihil temporibus, dignissimos explicabo officiis iure voluptas amet quo enim voluptatibus nulla beatae corrupti atque quaerat accusantium nemo ea, dolores id. Magni esse itaque incidunt at sunt iste nisi, ducimus dolore reiciendis voluptatem aperiam eligendi est officiis totam. Minima, odio.</p>
            </div>
        </div>
        <div className="storybottom">
            <Credit name="Gowtham" position="CEO" about="Driving the company’s vision, strategy, and overall growth while ensuring innovation and long-term success" img='/career_connect/people1.jpg'/>
            <Credit name="Abcdefg" position="Managing Director" about = "Overseeing daily operations, setting business objectives, and ensuring smooth coordination across all departments for sustainable growth" img="/career_connect/people2c.png"/>
            <Credit name="Hijklmn" position="Technical Director" about ="Leading the technology team, implementing innovative solutions, and ensuring that all technical aspects align with business goals." img="/career_connect/people3.jpg"/>
            <Credit name="Opqrstu" position="Associate Vice President (Sales)" about="Developing sales strategies, expanding customer relationships, and driving revenue growth through effective market positioning."img="/career_connect/people4.jpg"/>
            <Credit name="Shyam" position="Associate Vice President (Projects)" about="Managing key projects, ensuring timely execution, and maintaining quality standards while coordinating with multiple teams." img="/career_connect/people5.jpeg"/>
            <Credit name="Ganesh" position="Cheif Finance Officer (Accounts)" about="Handling financial planning, budgeting, and ensuring the company’s financial stability through efficient resource management" img="/career_connect/people6.jpg"/>
        </div>
    </div>
)
}

export default OurStory